//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteMenu
    {
        public int MenuID { get; set; }
        public string MenuName { get; set; }
        public string NavURL { get; set; }
        public Nullable<int> ParentMenuID { get; set; }
    }
}
